#ifndef OQS_SHA3_TEST_H
#define OQS_SHA3_TEST_H

#include <oqs/oqs.h>

OQS_STATUS SHA3_select();
OQS_STATUS SHAKE_select();

OQS_STATUS ISC_SHA3_All();
OQS_STATUS ISC_SHAKE_All();

OQS_STATUS ISC_SHA3_256();
OQS_STATUS ISC_SHA3_512();
OQS_STATUS ISC_SHAKE_128();
OQS_STATUS ISC_SHAKE_256();

#endif // OQS_SHA3_TEST_H
